// SPDX-License-Identifier: GPL-3.0-or-later
//! NixOS option semantics adapted from calamares-nixos-extensions 0.3.23.
//! No Python/C++ module or global-storage hooks are executed by this installer.
use crate::{Firmware, Kernel, Request, Settings, read_trusted};
use anyhow::{Context, Result, ensure};
use std::{collections::BTreeSet, fs, io::Write, os::unix::fs::OpenOptionsExt, path::Path};

pub fn nix_string(value: &str) -> String {
    // JSON quoting does not escape Nix interpolation. Escape dollars *after*
    // JSON encoding so a literal ${...} cannot become an executable expression.
    serde_json::to_string(value)
        .expect("string serialization")
        .replace("${", "\\${")
}

pub struct Template {
    pub flake: String,
    pub lock: Vec<u8>,
}
impl Template {
    pub fn load(settings: &Settings, hostname: &str) -> Result<Self> {
        let dir = Path::new(&settings.template_dir);
        let template = String::from_utf8(read_trusted(&dir.join("flake.nix.in"))?)?;
        let lock = read_trusted(&dir.join("flake.lock"))?;
        Self::parse(template, lock, hostname)
    }
    pub fn parse(template: String, lock: Vec<u8>, hostname: &str) -> Result<Self> {
        ensure!(
            template.matches("@HOSTNAME@").count() == 1,
            "Template must contain exactly one hostname placeholder"
        );
        let value: serde_json::Value = serde_json::from_slice(&lock)?;
        ensure!(value["version"] == 7, "Unsupported lock version");
        let root = value["root"].as_str().context("Missing lock root")?;
        let inputs = value["nodes"][root]["inputs"]
            .as_object()
            .context("Missing inputs")?;
        ensure!(
            inputs.keys().map(String::as_str).collect::<BTreeSet<_>>()
                == BTreeSet::from(["nixpkgs", "determinate", "fh"]),
            "Unexpected target flake inputs"
        );
        for name in ["nixpkgs", "determinate", "fh"] {
            let node = inputs[name]
                .as_str()
                .context("Expected a directly locked input")?;
            ensure!(
                value["nodes"][node]["locked"]["narHash"]
                    .as_str()
                    .is_some_and(|s| s.starts_with("sha256-")),
                "Unlocked input: {name}"
            );
        }
        Ok(Self {
            flake: template.replace("@HOSTNAME@", &nix_string(hostname)),
            lock,
        })
    }
    pub fn write(&self, dir: &Path) -> Result<()> {
        fs::write(dir.join("flake.nix"), &self.flake)?;
        fs::write(dir.join("flake.lock"), &self.lock)?;
        Ok(())
    }
}

pub fn configuration(request: &Request, settings: &Settings) -> String {
    let q = nix_string;
    let boot = match request.firmware {
        Firmware::Uefi => "boot.loader.systemd-boot.enable = true;\n  boot.loader.efi.canTouchEfiVariables = true;".into(),
        Firmware::Bios => format!("boot.loader.grub.enable = true;\n  boot.loader.grub.device = {};\n  boot.loader.grub.useOSProber = false;", q(&request.disk.path)),
    };
    let kernel = match settings.kernel {
        Kernel::Latest => "  boot.kernelPackages = pkgs.linuxPackages_latest;\n",
        Kernel::Lts => "",
    };
    let diagnostic = if settings.test_diagnostics {
        "  # Disposable QEMU verification only.\n  services.qemuGuest.enable = true;\n  boot.kernelParams = [ \"console=ttyS0,115200n8\" \"console=tty0\" ];\n"
    } else {
        ""
    };
    format!(
        r#"# Generated by the NixOS-focused Rust Calamares installer.
{{ config, pkgs, ... }}: {{
  imports = [ ./hardware-configuration.nix ];
  {boot}
{kernel}  networking.hostName = {hostname};
  networking.networkmanager.enable = true;
  time.timeZone = {timezone};
  i18n.defaultLocale = {locale};
  services.xserver.enable = true;
  services.xserver.xkb.layout = {keyboard};
  console.useXkbConfig = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;
  services.printing.enable = true;
  security.rtkit.enable = true;
  services.pipewire = {{ enable = true; alsa.enable = true; alsa.support32Bit = true; pulse.enable = true; }};
  users.mutableUsers = true;
  users.users.root.initialHashedPassword = "!";
  users.users.{username} = {{
    isNormalUser = true;
    description = {full_name};
    extraGroups = [ "networkmanager" "wheel" ];
    # A root-only file on the target, never a Nix store source path.
    hashedPasswordFile = "/etc/nixos-secrets/user-password.hash";
  }};
  programs.firefox.enable = true;
  environment.systemPackages = [ pkgs.kdePackages.kate ];
  nixpkgs.config.allowUnfree = {unfree};
  system.stateVersion = {state};
{diagnostic}}}
"#,
        hostname = q(&request.hostname),
        timezone = q(&request.timezone),
        locale = q(&request.locale),
        keyboard = q(&request.keyboard),
        username = q(&request.username),
        full_name = q(&request.full_name),
        unfree = request.allow_unfree,
        state = q(&settings.state_version)
    )
}

pub fn write_secret(path: &Path, hash: &str) -> Result<()> {
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)?;
    writeln!(file, "{hash}")?;
    file.sync_all()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn escape_interpolation_and_quotes() {
        assert_eq!(nix_string("${abort \"x\"}"), "\"\\${abort \\\"x\\\"}\"");
        assert_eq!(nix_string("x\\y"), "\"x\\\\y\"");
    }
    #[test]
    fn lock_and_placeholder_are_mandatory() {
        assert!(Template::parse("no placeholder".into(), b"{}".to_vec(), "test").is_err());
        assert!(
            Template::parse(
                "@HOSTNAME@".into(),
                br#"{"version":7,"root":"root","nodes":{"root":{"inputs":{}}}}"#.to_vec(),
                "test"
            )
            .is_err()
        );
    }
    #[test]
    fn secrets_are_exclusive_and_private() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("hash");
        write_secret(&path, "$6$test").unwrap();
        assert_eq!(
            fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        assert!(write_secret(&path, "overwrite").is_err());
    }
}
