# SPDX-License-Identifier: GPL-3.0-or-later
# Vanilla Hyprland: the compositor with its own upstream example configuration.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.calamares;
in
{
  options.calamares.hyprland.enable = lib.mkEnableOption "Hyprland with its upstream default configuration";
  config = lib.mkMerge [
    (lib.mkIf cfg.hyprland.enable {
      # uwsm starts graphical-session.target (and the session's own units),
      # which Hyprland alone never does. Tatami's module does the same.
      programs.hyprland = {
        enable = true;
        withUWSM = true;
      };
    })
    (lib.mkIf cfg.hyprland.enable {
      # Without a configuration Hyprland writes ~/.config/hypr/hyprland.lua
      # and shows an "autogenerated config" warning. The package's own
      # example is the same configuration without that marker.
      environment.etc."xdg/hypr/hyprland.lua".source =
        "${config.programs.hyprland.package}/share/hypr/hyprland.lua";
      # Programs the example's bindings use: terminal, file manager and
      # launcher, plus volume, brightness and media keys.
      environment.systemPackages = [
        pkgs.kitty
        pkgs.kdePackages.dolphin
        pkgs.hyprlauncher
        pkgs.wireplumber
        pkgs.brightnessctl
        pkgs.playerctl
      ];
    })
  ];
}
